title: Lifelong Leanner and Aspiring Software and Machine Learning Engineer 
author: Espoir Murhabazi Buzina 
email: espoir.mur@gmail.Com
description: > My Blog , a short description of me and stuff I did

# social links
twitter_username: @EspyMur
github_username:  @espoirMur
stackoverflow_username: espoir-murhabazi
medium_username: @EspyMur
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima 
